# Arithmetic

Arrays allow you to perform stack operations on data without having to use `for` loops. This is called *vectorisation* in NumPy. For all arithmetic operations between arrays of the same size, the operation is applied element by element:

In [1]:
import numpy as np


data = np.random.randn(7, 3)
data

array([[-0.04778788, -0.03971093, -1.71110236],
       [ 1.18746556,  0.5643496 ,  0.2859378 ],
       [-1.28686573,  0.40332209, -1.35913635],
       [-0.20140587,  1.60498449,  0.23844523],
       [-0.74730775,  0.11601887, -0.34109057],
       [-0.08702842, -1.1238352 ,  1.21659397],
       [ 0.54382846,  0.12373199, -0.02012923]])

In [2]:
1 / data

array([[-20.92580985, -25.18198603,  -0.58441857],
       [  0.84212969,   1.77195127,   3.49726411],
       [ -0.77708185,   2.47940793,  -0.73576135],
       [ -4.96509854,   0.62305898,   4.19383522],
       [ -1.3381368 ,   8.61928749,  -2.93177261],
       [-11.49049937,  -0.88981018,   0.82196692],
       [  1.83881514,   8.0819842 , -49.67899596]])

In [3]:
data**2

array([[2.28368106e-03, 1.57695769e-03, 2.92787128e+00],
       [1.41007445e+00, 3.18490476e-01, 8.17604243e-02],
       [1.65602341e+00, 1.62668712e-01, 1.84725163e+00],
       [4.05643252e-02, 2.57597521e+00, 5.68561274e-02],
       [5.58468871e-01, 1.34603783e-02, 1.16342779e-01],
       [7.57394581e-03, 1.26300555e+00, 1.48010090e+00],
       [2.95749391e-01, 1.53096057e-02, 4.05185952e-04]])

Comparison of two arrays:

In [4]:
data2 = np.random.randn(7, 3)
data > data2

array([[ True, False, False],
       [ True,  True, False],
       [False,  True, False],
       [ True,  True,  True],
       [False, False,  True],
       [ True, False,  True],
       [ True,  True, False]])