# Arithmetic

Arrays allow you to perform stack operations on data without having to use `for` loops. This is called *vectorisation* in NumPy. For all arithmetic operations between arrays of the same size, the operation is applied element by element:

In [1]:
import numpy as np


rng = np.random.default_rng()
data = rng.random((7, 3))
data

array([[0.29244924, 0.32072447, 0.30934757],
       [0.89174829, 0.84865903, 0.8219735 ],
       [0.73972395, 0.139968  , 0.7551268 ],
       [0.30778384, 0.16360734, 0.05536757],
       [0.26396912, 0.08043216, 0.24179992],
       [0.93238137, 0.02947168, 0.26255382],
       [0.90513945, 0.50250317, 0.2176639 ]])

In [2]:
1 / data

array([[ 3.41939682,  3.11794111,  3.23260989],
       [ 1.12139267,  1.17832953,  1.21658423],
       [ 1.35185566,  7.14449008,  1.3242809 ],
       [ 3.24903344,  6.11219537, 18.06111538],
       [ 3.78832187, 12.43283799,  4.13565066],
       [ 1.0725225 , 33.93087472,  3.80874296],
       [ 1.10480214,  1.9900372 ,  4.59423914]])

In [3]:
data**2

array([[8.55265575e-02, 1.02864183e-01, 9.56959163e-02],
       [7.95215015e-01, 7.20222151e-01, 6.75640436e-01],
       [5.47191516e-01, 1.95910415e-02, 5.70216487e-01],
       [9.47308944e-02, 2.67673603e-02, 3.06556738e-03],
       [6.96796977e-02, 6.46933218e-03, 5.84672015e-02],
       [8.69335024e-01, 8.68580127e-04, 6.89345065e-02],
       [8.19277417e-01, 2.52509435e-01, 4.73775726e-02]])

Comparison of two arrays:

In [4]:
data2 = rng.random((7, 3))
data > data2

array([[False,  True, False],
       [ True,  True,  True],
       [ True, False,  True],
       [ True, False, False],
       [False, False, False],
       [ True, False, False],
       [ True, False, False]])