# Sort

As in Python’s `list`, NumPy arrays can be sorted in-place using the [numpy.sort](https://numpy.org/doc/stable/reference/generated/numpy.sort.html) method. You can sort any one-dimensional section of values in a multidimensional array in place along an axis by passing the axis number to sort:

In [4]:
import numpy as np

data = np.random.randn(7, 3)

data

array([[ 0.01030144,  0.78524872,  0.42930263],
       [-1.51182764,  0.16973497, -0.6294608 ],
       [-1.63687566,  2.89978519, -1.12282476],
       [-0.23121837,  0.40594707, -0.1667278 ],
       [ 1.57718982, -0.4898681 , -0.38596701],
       [ 0.92491973, -0.69984905, -1.66848346],
       [-0.87552462, -0.04699234,  1.33797794]])

In [9]:
data.sort(0)

data

array([[-1.63687566, -0.69984905, -1.66848346],
       [-1.51182764, -0.4898681 , -1.12282476],
       [-0.87552462, -0.04699234, -0.6294608 ],
       [-0.23121837,  0.16973497, -0.38596701],
       [ 0.01030144,  0.40594707, -0.1667278 ],
       [ 0.92491973,  0.78524872,  0.42930263],
       [ 1.57718982,  2.89978519,  1.33797794]])

`np.sort`, on the other hand, returns a sorted copy of an array instead of changing the array in place:

In [7]:
np.sort(data, axis=1)

array([[ 0.01030144,  0.42930263,  0.78524872],
       [-1.51182764, -0.6294608 ,  0.16973497],
       [-1.63687566, -1.12282476,  2.89978519],
       [-0.23121837, -0.1667278 ,  0.40594707],
       [-0.4898681 , -0.38596701,  1.57718982],
       [-1.66848346, -0.69984905,  0.92491973],
       [-0.87552462, -0.04699234,  1.33797794]])

In [10]:
data

array([[-1.63687566, -0.69984905, -1.66848346],
       [-1.51182764, -0.4898681 , -1.12282476],
       [-0.87552462, -0.04699234, -0.6294608 ],
       [-0.23121837,  0.16973497, -0.38596701],
       [ 0.01030144,  0.40594707, -0.1667278 ],
       [ 0.92491973,  0.78524872,  0.42930263],
       [ 1.57718982,  2.89978519,  1.33797794]])