# Mathematical and statistical methods

A number of mathematical functions that calculate statistics over an entire array or over the data along an axis are accessible as methods of the array class. So you can use aggregations such as sum, mean and standard deviation by either calling the array instance method or using the top-level NumPy function.

Below I generate some random data and calculate some aggregated statistics:

In [1]:
import numpy as np


data = np.random.randn(7, 3)

data

array([[ 0.16673777,  0.98120647, -0.27075733],
       [-1.59965964, -0.440924  ,  0.63509529],
       [-0.52089534, -1.50217927,  0.66333717],
       [-0.57253028,  0.91016243, -0.62618228],
       [ 0.68603489,  0.30021146, -0.68244562],
       [ 1.64629059,  1.82493142,  0.50776089],
       [-0.41753316,  0.8941741 ,  0.35598082]])

In [2]:
data.mean()

np.float64(0.13994363775784308)

In [3]:
np.mean(data)

np.float64(0.13994363775784308)

In [4]:
data.sum()

np.float64(2.9388163929147044)

Functions like `mean` and `sum` require an optional axis argument that calculates the statistic over the specified axis, resulting in an array with one less dimension:

In [5]:
data.mean(axis=0)

array([-0.08736502,  0.42394037,  0.08325556])

In [6]:
data.sum(axis=0)

array([-0.61155517,  2.96758262,  0.58278894])

With `data.mean(0)`, which is the same as `data.mean(axis=0)`, the mean is calculated over the rows, while `data.sum(0)` calculates the sum over the rows.

Other methods like `cumsum` and `cumprod`, however, do not aggregate but create a new array with the intermediate results.

In multidimensional arrays, accumulation functions such as `cumsum` and `cumprod` return an array of the same size but with the partial aggregates calculated along the specified axis:

In [7]:
data.cumsum()

array([ 0.16673777,  1.14794423,  0.8771869 , -0.72247274, -1.16339674,
       -0.52830145, -1.04919679, -2.55137605, -1.88803888, -2.46056916,
       -1.55040673, -2.17658901, -1.49055412, -1.19034265, -1.87278827,
       -0.22649768,  1.59843374,  2.10619463,  1.68866148,  2.58283558,
        2.93881639])

In [8]:
data.cumprod()

array([ 1.66737767e-01,  1.63604175e-01, -4.42970305e-02,  7.08601720e-02,
       -3.12439504e-02, -1.98428858e-02,  1.03360667e-02, -1.55266251e-02,
       -1.02993876e-02,  5.89671129e-03,  5.36696509e-03, -3.36069844e-03,
       -2.30555639e-03, -6.92154459e-04,  4.72357778e-04,  7.77638167e-04,
        1.41913632e-03,  7.20581930e-04, -3.00866850e-04, -2.69027345e-04,
       -9.57685740e-05])

Basic statistical methods for arrays are:

Method | Description
:----- | :----------
`sum` | Sum of all elements in the array or along an axis.
`mean` | Arithmetic mean; for arrays with length zero, `NaN` is returned.
`std`, `var` | Standard deviation and variance respectively
`min`, `max` | Minimum and maximum
`argmin`, `argmax` | Indices of the minimum and maximum elements respectively
`cumsum` | Cumulative sum of the elements, starting with `0`
`cumprod` | Cumulative product of the elements, starting with `1`