# Universal functions (`ufunc`)

A universal function, or `ufunc`, is a function that performs element-wise operations on data in `ndarrays`. They can be thought of as fast vectorised wrappers for simple functions that take one or more scalar values and produce one or more scalar results.

Many `ufuncs` are simple element-wise transformations, such as [sqrt](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html) or [exp](https://numpy.org/doc/stable/reference/generated/numpy.exp.html):

In [1]:
import numpy as np


data = np.arange(10)

In [2]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(data)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.exp(data)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

These are called single-digit ufuncs. Others, such as [add](https://numpy.org/doc/stable/reference/generated/numpy.add.html) or [maximum](https://numpy.org/doc/stable/reference/generated/numpy.maximum.html), take two arrays (i.e. binary ufuncs) and return a single array as the result:

In [5]:
x = np.random.randn(8)

In [6]:
y = np.random.randn(8)

In [7]:
x

array([ 0.44578824,  1.05756247, -0.91137028, -0.95006139, -0.07310552,
        0.39838185, -0.07726907, -0.56184031])

In [8]:
y

array([-0.63414707, -0.41705939, -0.40171689, -0.60919983,  1.5244012 ,
       -1.46477065, -0.12212396,  0.92888368])

In [9]:
np.maximum(x, y)

array([ 0.44578824,  1.05756247, -0.40171689, -0.60919983,  1.5244012 ,
        0.39838185, -0.07726907,  0.92888368])

Here `numpy.maximum` calculated the element-wise maximum of the elements in `x` and `y`.

Some `ufunc`, such as [modf](https://numpy.org/doc/stable/reference/generated/numpy.modf.html), a vectorised version of the built-in Python [divmod](https://docs.python.org/3/library/functions.html#divmod), return multiple arrays: the fractional and integral parts of a floating-point array:

In [10]:
data = x * 5

In [11]:
data

array([ 2.22894121,  5.28781235, -4.55685142, -4.75030693, -0.36552761,
        1.99190924, -0.38634536, -2.80920154])

In [12]:
remainder, whole_part = np.modf(x)

In [13]:
remainder

array([ 0.44578824,  0.05756247, -0.91137028, -0.95006139, -0.07310552,
        0.39838185, -0.07726907, -0.56184031])

In [14]:
whole_part

array([ 0.,  1., -0., -0., -0.,  0., -0., -0.])

Ufuncs accept an optional `out` argument that allows you to transfer your results to an existing array instead of creating a new one:

In [15]:
out = np.zeros_like(data)

In [16]:
np.add(data, 1)

array([ 3.22894121,  6.28781235, -3.55685142, -3.75030693,  0.63447239,
        2.99190924,  0.61365464, -1.80920154])

In [17]:
np.add(data, 1, out=out)

array([ 3.22894121,  6.28781235, -3.55685142, -3.75030693,  0.63447239,
        2.99190924,  0.61365464, -1.80920154])

In [18]:
out

array([ 3.22894121,  6.28781235, -3.55685142, -3.75030693,  0.63447239,
        2.99190924,  0.61365464, -1.80920154])

Some single-digit ufuncs:

Function | Description
:------- | :----------
`abs`, `fabs` | calculates the absolute value element by element for integer, floating point or complex values
`sqrt` | calculates the square root of each element (corresponds to `data ** 0,5`)
`square` | calculates the square of each element (corresponds to `data ** 2`)
`exp` | calculates the exponent e<sup>x</sup> of each element
`log`, `log10`, `log2`, `log1p` | Natural logarithm (base e), log base 10, log base 2 and log(1 + x) respectively
`sign` | calculates the sign of each element: `1` (positive), `0` (zero), or `-1` (negative)
`ceil` | calculates the upper limit of each element (i.e. the smallest integer greater than or equal to this number)
`floor` | calculates the lower limit of each element (i.e. the largest integer less than or equal to each element)
`rint` | rounds elements to the nearest integer, preserving the `dtype`
`modf` | returns the fractional and integer parts of the array as separate arrays
`isnan` | returns a boolean array indicating whether each value is `NaN` (Not a Number)
`isfinite`, `isinf` | returns a boolean array indicating whether each element is finite (not-`inf`, not-`NaN`) or infinite, respectively
`cos`, `cosh`, `sin`, `sinh`, `tan`, `tanh` | regular and hyperbolic trigonometric functions
`arccos`, `arccosh`, `arcsin`, `arcsinh`, `arctan`, `arctanh` | Inverse trigonometric functions
`logical_not` | calculates the truth value of `not x` element by element (corresponds to `~data`)

Some binary universal functions:

Function | Description
:------- | :----------
`add` | add corresponding elements in arrays
`subtract` | subtracts elements in the second array from the first array
`multiply` | multiply array elements
`divide`, `floor_divide` | divide or truncate the remainder
`power` | increases elements in the first array to the powers specified in the second array
`maximum`, `fmax` | element-wise maximum; `fmax` ignores `NaN`
`minimum`, `fmin` | element-wise minimum; `fmin` ignores `NaN`
`mod` | element-wise modulus (remainder of the division)
`copysign` | copies the sign of the values in the second argument to the values in the first argument
`greater`, `greater_equal`, `less`, `less_equal`, `equal`, `not_equal` | perform element-wise comparisons that result in a Boolean array (corresponds to the infix operators `>`, `>=`, `<`, `<=`, `==`, `!=`)
`logical_and` | calculates the element-wise truth value of the logical operation AND (`&`)
`logical_or` | calculates the element-wise truth value of the logical operation OR (`|`)
`logical_xor` | calculates the element-wise truth value of the logical operation XOR (`^`)

<div class="alert alert-block alert-info">
    
**Note:**

A complete overview of binary universal functions can be found in [Universal functions (ufunc)](https://numpy.org/doc/stable/reference/ufuncs.html).
</div>